name: portofolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  neubrutalism_ui: ^2.0.2
  responsive_framework: ^1.5.1
  go_router: ^14.8.0
  url_launcher: ^6.2.3
  websafe_svg: ^3.0.1+10
  dynamic_path_url_strategy: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/asme/
    - assets/images/dt/
    - assets/images/fengshui/
    - assets/images/ka/
    - assets/images/kresna/
    - assets/images/labscib/
    - assets/images/mediplus/
    - assets/images/my_ambarrukmo/
    - assets/images/reps_id/
    - assets/images/tda/
    - assets/svgs/

  fonts:
    - family: OverpassMono
      fonts:
        - asset: assets/fonts/overpass_mono/OverpassMono-Regular.ttf
        - asset: assets/fonts/overpass_mono/OverpassMono-Bold.ttf
          weight: 700
          
    - family: VcrOsdMono
      fonts:
        - asset: assets/fonts/vcr_osd_mono/VCR_OSD_MONO_1.001.ttf
